### PR TITLE
Unity Package support

### PR DESCRIPTION
**Pull request by milos-clevertap**

### CODE REVIEW

**Comment by nzagorchev** [comment]
@milos1290 Do we really need the meta files?

**Comment by milos-clevertap** [comment]
> @milos1290 Do we really need the meta files?

Yeah we need meta files in git

**Comment by nzagorchev** [comment]
Please add a description of what this PR adds. 
For the package, please add more details if structure changes will be done, assembly definitions etc.

**Comment by nzagorchev** [comment]
As part of this PR:
- Add assembly definitions, ensure csproj is generated and the local package works fine
- Build script and export
- Sample app with local package for developing and exporting

Let me know when it is ready for review. Thanks!

**Pull request merged**
